# Test configuration for GCS bucket: geoip2
# Project: outdoorsafetylab
log:
  dev: true

geoip2:
  edition: GeoLite2-City
  renew: ""  # Disable auto-renewal for testing
  cloud_storage:
    provider: gcs
    bucket: geoip2
    key_prefix: geoip/

port: 8080
endpoint: /v1

# Use local Redis for testing
redis:
  host: 127.0.0.1
  port: 6379
  pass: ""
  expire: 300s